---
# requirements.yml
# This requirements file lists all the collections from
# the red hat ansible automation hub that we want installed on Tower

collections:
- ansible.netcommon
- ansible.posix
- ansible.utils
- ansible.windows
- ansible.tower
- ansible.controller
- redhat_cop.tower_configuration
- redhat.satellite
- redhat.satellite_operations
- redhat.rhel_idm
- redhat.rhel_system_roles
- redhat.insights
- azure.azcollection

